# Site settings
title: Kevin's Blog
header-img: img/home-bg.jpg
email: zhao182y@sina.com
description: "Tech Blog"
github_username:  kevin--zhao
production_url : http://kevin--zhao.github.io
# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
